### ISSUE TITLE
运行“python typora.py {installRoot}/Typora/resources/app.asar workstation/outfile/ ”报错

### ISSUE THREAD

**Issue by Poker-Pan** [Mas0nShi/typoraCracker#66] opened 2022-04-13 08:38 UTC
![H50R%{L7{UQBU}8(W4SRVX4](https://user-images.githubusercontent.com/49545046/163135834-cf6e335e-9498-403c-a801-7ad305065ceb.png)

What should I do if such a mistake occurs

**Comment by Mas0nShi** [comment] 2022-04-13 08:40
Duplicate of #64

**Comment by Poker-Pan** [comment] 2022-04-13 08:42
Thanks   I tried the new version

**Comment by Poker-Pan** [comment] 2022-04-13 08:49
![P L~FNW18Z03LN}Y_A{0M4B](https://user-images.githubusercontent.com/49545046/163137892-ab7b3db4-dd01-4460-8638-175f3f9a3b7b.png)
I have downloaded the latest version typoracrack-1.2.4-WIN-x86 and the result is the same

**Comment by Poker-Pan** [comment] 2022-04-13 08:57
I've done it thank you

**Comment by Mas0nShi** [comment] 2022-04-13 09:02
well

**Closed** 2022-04-13 12:16 UTC
Labels: question
