### ISSUE TITLE
1.2.4版本激活失败

### ISSUE THREAD

**Issue by kerojiang** [Mas0nShi/typoraCracker#59] opened 2022-04-06 07:40 UTC
**Describe the bug**
 - OS: [manjaro linux x64]
 - Version []
用生成的激活码无法激活
**To Reproduce**

❯ python typora.py ~/Apps/typora/resources/app.asar build
2022-04-06 15:17:23.119 | INFO     | __main__:extractWdec:76 - extract asar file: /home/jie/Apps/typora/resources/app.asar
2022-04-06 15:17:23.119 | SUCCESS  | __main__:extractWdec:79 - extract ended.
2022-04-06 15:17:23.120 | INFO     | __main__:extractWdec:81 - read Directory: build/typoraCrackerTemp
2022-04-06 15:17:23.120 | INFO     | __main__:extractWdec:89 - set Directory: build/dec_app
2022-04-06 15:17:23.120 | INFO     | __main__:extractWdec:96 - open file: atom.js
2022-04-06 15:17:23.122 | SUCCESS  | __main__:extractWdec:104 - decrypt and save file: atom.js
2022-04-06 15:17:23.122 | INFO     | __main__:extractWdec:96 - open file: main.node
2022-04-06 15:17:23.122 | SUCCESS  | __main__:extractWdec:104 - decrypt and save file: main.node
2022-04-06 15:17:23.122 | INFO     | __main__:extractWdec:96 - open file: package.json
2022-04-06 15:17:23.122 | SUCCESS  | __main__:extractWdec:104 - decrypt and save file: package.json
2022-04-06 15:17:23.122 | SUCCESS  | __main__:main:182 - Done!

❯ python typora.py -u build/dec_app build                
2022-04-06 15:18:18.030 | WARNING  | __main__:_mkDir:42 - May FolderExists: build
2022-04-06 15:18:18.031 | INFO     | __main__:packWenc:141 - set outFilePath: build/app.asar
2022-04-06 15:18:18.031 | INFO     | __main__:packWenc:151 - open file: atom.js
2022-04-06 15:18:18.033 | SUCCESS  | __main__:packWenc:156 - encrypt and save file: atom.js
2022-04-06 15:18:18.033 | INFO     | __main__:packWenc:151 - open file: main.node
2022-04-06 15:18:18.033 | SUCCESS  | __main__:packWenc:156 - encrypt and save file: main.node
2022-04-06 15:18:18.033 | INFO     | __main__:packWenc:151 - open file: package.json
2022-04-06 15:18:18.033 | SUCCESS  | __main__:packWenc:156 - encrypt and save file: package.json
2022-04-06 15:18:18.034 | INFO     | __main__:packWenc:158 - ready to pack
2022-04-06 15:18:18.034 | SUCCESS  | __main__:packWenc:160 - pack done
2022-04-06 15:18:18.034 | SUCCESS  | __main__:main:182 - Done!

❯ cp ~/Apps/typora/resources/app.asar ~/Apps/typora/resources/app.asar.bak 

❯ mv build/app.asar ~/Apps/typora/resources/app.asar

❯ node example/keygen.js 
2P5R7X-AR2NV9-VW32RA-3V2WET

**Screenshots**

![截图-2022-04-06_15-38-56](https://user-images.githubusercontent.com/5567031/161921560-d7628d30-d506-4fd1-a5d2-289909353a1b.png)

**Additional context**

**Comment by Mas0nShi** [comment] 2022-04-06 07:53
Duplicate of #41 #42 #43
请仔细阅读 #25

**Comment by Mas0nShi** [comment] 2022-04-06 07:59
衍生作品
https://github.com/SnapdragonLee/TyporaCrack

**Closed** 2022-04-06 08:01 UTC
Labels: invalid

**Comment by Mas0nShi** [comment] 2022-04-06 08:19
answer: #60
